export const INDIAN_NAMES = [
  "Editorial Desk",
  "Business Editorial Team",
  "News Desk India",
  "Media Insights Team",
  "Digital Editorial Desk",
  "Research & Analysis Team",
  "Content Bureau",
  "Business Insights Desk",
  "India News Network",
  "Editorial Board",
  "Priya Khanna",
  "Neha Agarwal",
  "Simran Kaur",
  "Ananya Verma",
  "Riya Sharma",
  "Kavya Mehta",
  "Pooja Bansal",
  "Sneha Kapoor",
  "Isha Arora",
  "Shreya Gupta",
  "Aarav Mehta",
  "Rohan Sharma",
  "Kunal Verma",
  "Aditya Singh",
  "Nikhil Bansal",
  "Arjun Kapoor",
  "Kartik Gupta",
  "Rajat Malhotra",
  "Saurabh Jain",
  "Kinjal Gupta",
  "Vivek Mishra"
];
