/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ListiclesRouteImport } from './routes/listicles'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ListicleSlugRouteImport } from './routes/listicle.$slug'
import { Route as CategoryCatRouteImport } from './routes/category.$cat'
import { Route as ArticleIdRouteImport } from './routes/article.$id'
import { Route as AdminMagazineRouteImport } from './routes/admin/magazine'
import { Route as AdminListiclesRouteImport } from './routes/admin/listicles'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AuthAdminLoginRouteImport } from './routes/auth/admin/login'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ListiclesRoute = ListiclesRouteImport.update({
  id: '/listicles',
  path: '/listicles',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ListicleSlugRoute = ListicleSlugRouteImport.update({
  id: '/listicle/$slug',
  path: '/listicle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCatRoute = CategoryCatRouteImport.update({
  id: '/category/$cat',
  path: '/category/$cat',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMagazineRoute = AdminMagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => AdminRoute,
} as any)
const AdminListiclesRoute = AdminListiclesRouteImport.update({
  id: '/listicles',
  path: '/listicles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AuthAdminLoginRoute = AuthAdminLoginRouteImport.update({
  id: '/auth/admin/login',
  path: '/auth/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/listicles': typeof ListiclesRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/listicles': typeof AdminListiclesRoute
  '/admin/magazine': typeof AdminMagazineRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$cat': typeof CategoryCatRoute
  '/listicle/$slug': typeof ListicleSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/listicles': typeof ListiclesRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/listicles': typeof AdminListiclesRoute
  '/admin/magazine': typeof AdminMagazineRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$cat': typeof CategoryCatRoute
  '/listicle/$slug': typeof ListicleSlugRoute
  '/admin': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/listicles': typeof ListiclesRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/listicles': typeof AdminListiclesRoute
  '/admin/magazine': typeof AdminMagazineRoute
  '/article/$id': typeof ArticleIdRoute
  '/category/$cat': typeof CategoryCatRoute
  '/listicle/$slug': typeof ListicleSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/admin/login': typeof AuthAdminLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/latest'
    | '/listicles'
    | '/publish'
    | '/search'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/listicles'
    | '/admin/magazine'
    | '/article/$id'
    | '/category/$cat'
    | '/listicle/$slug'
    | '/admin/'
    | '/auth/admin/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/latest'
    | '/listicles'
    | '/publish'
    | '/search'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/listicles'
    | '/admin/magazine'
    | '/article/$id'
    | '/category/$cat'
    | '/listicle/$slug'
    | '/admin'
    | '/auth/admin/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/latest'
    | '/listicles'
    | '/publish'
    | '/search'
    | '/admin/articles'
    | '/admin/categories'
    | '/admin/listicles'
    | '/admin/magazine'
    | '/article/$id'
    | '/category/$cat'
    | '/listicle/$slug'
    | '/admin/'
    | '/auth/admin/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  LatestRoute: typeof LatestRoute
  ListiclesRoute: typeof ListiclesRoute
  PublishRoute: typeof PublishRoute
  SearchRoute: typeof SearchRoute
  ArticleIdRoute: typeof ArticleIdRoute
  CategoryCatRoute: typeof CategoryCatRoute
  ListicleSlugRoute: typeof ListicleSlugRoute
  AuthAdminLoginRoute: typeof AuthAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listicles': {
      id: '/listicles'
      path: '/listicles'
      fullPath: '/listicles'
      preLoaderRoute: typeof ListiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/listicle/$slug': {
      id: '/listicle/$slug'
      path: '/listicle/$slug'
      fullPath: '/listicle/$slug'
      preLoaderRoute: typeof ListicleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$cat': {
      id: '/category/$cat'
      path: '/category/$cat'
      fullPath: '/category/$cat'
      preLoaderRoute: typeof CategoryCatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/magazine': {
      id: '/admin/magazine'
      path: '/magazine'
      fullPath: '/admin/magazine'
      preLoaderRoute: typeof AdminMagazineRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/listicles': {
      id: '/admin/listicles'
      path: '/listicles'
      fullPath: '/admin/listicles'
      preLoaderRoute: typeof AdminListiclesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/admin/login': {
      id: '/auth/admin/login'
      path: '/auth/admin/login'
      fullPath: '/auth/admin/login'
      preLoaderRoute: typeof AuthAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminListiclesRoute: typeof AdminListiclesRoute
  AdminMagazineRoute: typeof AdminMagazineRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminListiclesRoute: AdminListiclesRoute,
  AdminMagazineRoute: AdminMagazineRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  LatestRoute: LatestRoute,
  ListiclesRoute: ListiclesRoute,
  PublishRoute: PublishRoute,
  SearchRoute: SearchRoute,
  ArticleIdRoute: ArticleIdRoute,
  CategoryCatRoute: CategoryCatRoute,
  ListicleSlugRoute: ListicleSlugRoute,
  AuthAdminLoginRoute: AuthAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
